### ISSUE TITLE
Incomplete/inconsistent dependencies

### ISSUE THREAD

**Issue by bramcuyx** [earthspecies/biodenoising-datasets#1]
There is an inconsistency in the requirements.txt and the pyproject.toml in the required packages (i.e. asteroid is present in requirements.txt but not in pyproject.toml). Both also miss the dependency on pyyaml, which is imported in the run.py file.

**Comment by nkundiushuti** [comment]
thanks for raising this issue. I will fix it soon. if you prefer to do a PR instead, you're more than welcomed!

**Comment by bramcuyx** [comment]
I made a pull request with these changes!

**Comment by nkundiushuti** [comment]
solved by #2
